# Generated by Django 3.2 on 2022-04-23 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_name_product_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
